val buffer_size : int
val strict : bool
val max_method_size : int
val max_uri_size : int
val max_version_digit_size : int
val max_header_size : int
val max_content_size : int
val max_chunk_size : int
val address : Unix.inet_addr
val port : int
val backlog : int
